//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;

namespace ODataV3.Models
{

    public class LedgerEntry
    {

        #region Properties

        public Guid Id { get; set; }

        public Guid ScenarioId { get; set; }

        //[NotMapped]
        public LedgerEntryTypes LedgerEntryType { get; set; }

        [StringLength(250)]
        public string Description { get; set; }

        public decimal Amount { get; set; }

        public int? Conversion { get; set; }

        public decimal AnnualIncrease { get; set; }

        public DateTime? DateApplicable { get; set; }

        public Guid? CreatedById { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime DateCreated { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime DateUpdated { get; set; }

        [StringLength(250)]
        public string Notes { get; set; }


        #endregion

        #region Constructors

        public LedgerEntry()
        {
            DateCreated = DateTime.Now;
            DateUpdated = DateTime.Now;

        }

        public LedgerEntry(LedgerEntryTypes ledgerEntryType, string description, decimal amount, Nullable<int> conversion, decimal annualIncrease, Nullable<System.DateTime> dateApplicable, string notes) : this()
        {

            Id = Guid.NewGuid();
            LedgerEntryType = ledgerEntryType;
            Description = description;
            Amount = amount;
            Conversion = conversion;
            AnnualIncrease = annualIncrease;
            DateApplicable = dateApplicable;
            Notes = notes;
        }

        #endregion

        #region Public Methods

        /// <summary>
        /// Clones the object.
        /// </summary>
        /// <returns>Returns a clone of the current object.</returns>
        public LedgerEntry Clone()
        {
            var copy = (LedgerEntry)MemberwiseClone();
            return copy;
        }

        #endregion

    }

}